openapi: 3.0.0
info:
  version: "1.0.0"
  title: "Expense API"
paths:
  /reimburse:
    post:
      description: Puts in the reimbursement request
      requestBody:
        description: the reimbursement details
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                event:
                  type: string
                person:
                  type: string
                dateOfPurchase:
                  type: string
                totalAmount:
                  type: string
                description:
                  type: string
                other:
                  type: string
              required:
                - event
                - person
                - dateOfPurchase
                - totalAmount
                - description

      responses:
        '200':
          description: Returns the result from Comprehend
          content:
            application/json:
              schema:
                type: object
                properties:
                  body:
                    type: string
                  headers:
                    type: string
                    example: {'header':'value'}
                  statusCode:
                    type: integer
                  isBase64Encoded:
                    type: boolean
        '400':
          description: Invalid characters in "user" were provided.
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: 200
        uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ExpenseFunction.Arn}/invocations"
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
    options:
      summary: CORS support
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: "{\n  \"statusCode\" : 200\n}\n"
        responses:
          default:
            statusCode: '200'
            responseTemplates:
              application/json: "{}\n"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: http://umabahl.com
              method.response.header.Access-Control-Allow-Methods:
                - OPTIONS
                - POST
              method.response.header.Access-Control-Allow-Headers:
                - Content-Type
                - X-Amz-Date
                - Authorization
                - X-Api-Key
                - X-Amz-Security-Token
      responses:
        '200':
          description: Default response for CORS method
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
