AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    acm-expenses
    
    keep track of all acm expenses 

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 5
        AutoPublishAlias: live # More info about Safe Deployments: https://github.com/awslabs/serverless-application-model/blob/master/docs/safe_lambda_deployments.rst
        DeploymentPreference:
            Type: Linear10PercentEvery1Minute 


Resources:

    ExpenseFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: ./first_function # .aws-sam/build/template.yaml  # first_function/build/
            Handler: app.lambda_handler
            Runtime: python3.7 # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
            Environment:
                Variables:
                    TABLE_NAME: !Ref DynamoDBTable
#                    POLICY_ARN: !Ref SESAuthorizationPolicy
            Events:
                Post:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /reimburse
                        Method: POST
                        RestApiId: !Ref ExpenseApi

            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonDynamoDBFullAccess
                - Version: '2012-10-17'
                  Id: APIgatewayPolicy
                  Statement:
                      - Sid: Stmt1467321765000
                        Effect: Allow
                        Action:
                            - apigateway:*
                        Resource:
                             - "*"
                - Id: SESAuthorizationPolicy
                  Version: '2012-10-17'
                  Statement:
                      - Sid: AuthorizeService
                        Effect: Allow
                        Resource: "*"
#                            !Sub "arn:aws:ses:${AWS::Region}:${AWS::AccountId}:identity/umabahl.com"
#                        Principal:
#                            Service:
#                                - lambda.amazonaws.com
                        Action:
                            - 'SES:SendEmail'

    ApiGatewayInvokeLambdaPermission:
        Type: "AWS::Lambda::Permission"
        Properties:
            Action: lambda:InvokeFunction
            FunctionName: !GetAtt
                - ExpenseFunction
                - Arn
            Principal: apigateway.amazonaws.com
            SourceArn: !Join [
                "", [
                "arn:aws:execute-api:",
                {"Ref": "AWS::Region"}, ":",
                {"Ref": "AWS::AccountId"}, ":",
                !Ref ExpenseApi, "/*/*/*"
      ]
      ]

    ExpenseApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: stage1
            EndpointConfiguration: REGIONAL
            Cors:
                AllowOrigin: "'http://umabahl.com'"
            DefinitionBody:
                openapi: 3.0.0
                info:
                    version: "1.0.0"
                    title: "Expense API"
                paths:
                    /reimburse:
                        post:
                            description: Puts in the reimbursement request
                            requestBody:
                                description: the reimbursement details
                                required: true
                                content:
                                    application/x-www-form-urlencoded:
                                        schema:
                                            type: object
                                            properties:
                                                event:
                                                    type: string
                                                person:
                                                    type: string
                                                dateOfPurchase:
                                                    type: string
                                                totalAmount:
                                                    type: string
                                                description:
                                                    type: string
                                                other:
                                                    type: string
                                            required:
                                                - event
                                                - person
                                                - dateOfPurchase
                                                - totalAmount
                                                - description

                            responses:
                                '200':
                                    description: Returns the result from Comprehend
                                    content:
                                        application/json:
                                            schema:
                                                type: object
                                                properties:
                                                    body:
                                                        type: string
                                                    headers:
                                                        type: string
                                                        example: {'header':'value'}
                                                    statusCode:
                                                        type: integer
                                                    isBase64Encoded:
                                                        type: boolean
                                '400':
                                    description: Invalid characters in "user" were provided.
                            x-amazon-apigateway-integration:
                                responses:
                                    default:
                                        statusCode: 200
                                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ExpenseFunction.Arn}/invocations"
                                passthroughBehavior: when_no_match
                                httpMethod: POST
                                type: aws_proxy
    DynamoDBTable:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
                - AttributeName: "ReimbursementSeeker"
                  AttributeType: "S"
                - AttributeName: "DateAdded"
                  AttributeType: "S"
            KeySchema:
                - AttributeName: "ReimbursementSeeker"
                  KeyType: "HASH"
                - AttributeName: "DateAdded"
                  KeyType: "RANGE"
            ProvisionedThroughput:
                ReadCapacityUnits: "10"
                WriteCapacityUnits: "10"


